jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code Plugin\n\n"
  clouds:
    - docker:
        name: "docker"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"

unclassified:
  location:
    adminAddress: ${JENKINS_LOCATION_ADMIN_ADDRESS}
    url: ${JENKINS_LOCATION_URL}

